<a href="https://colab.research.google.com/github/L1ght6/LabsKSVD/blob/main/%D0%93%D0%BE%D1%80%D0%B0_hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://github.com/L1ght6/LabsKSVD/blob/main/%D0%93%D0%BE%D1%80%D0%B0_hw1.ipynb

In [1]:
import numpy as np

In [2]:
# Завдання 1. Створіть одновимірний масив (вектор) з першими 20-ма натуральними числами та виведіть його значення.
task1_array = np.arange(1, 21)
print("Вектор з першими 20-ма натуральними числами:\n", task1_array)

Вектор з першими 20-ма натуральними числами:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [3]:
# Завдання 2. Створіть двовимірний масив (матрицю) розміром 4x4, заповніть його одиницями та виведіть його значення.
task2_matrix = np.ones((4, 4))
print("Матриця 4x4 з одиницями:\n", task2_matrix)

Матриця 4x4 з одиницями:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
# Завдання 3. Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від -1 до 1 та виведіть його значення.
task3_matrix = np.random.uniform(-1, 1, (5, 5))
print("Матриця 5x5 з дійсними числами від -1 до 1:\n", task3_matrix)

Матриця 5x5 з дійсними числами від -1 до 1:
 [[-0.46481021  0.40681863 -0.21333052 -0.87462546  0.47854258]
 [ 0.91317174 -0.00623735 -0.45740686  0.11154369 -0.19047534]
 [ 0.8956532   0.43885883  0.50225978  0.48219788 -0.25276418]
 [ 0.19946452 -0.04328607 -0.9524185   0.7950196  -0.04110367]
 [ 0.00177469 -0.93802143 -0.11329698  0.16857363  0.37937945]]


In [5]:
# Завдання 4. Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
task4_matrix = np.random.rand(3, 3)
print("Матриця 3x3 з дійсними числами від 0 до 1:\n", task4_matrix)

Матриця 3x3 з дійсними числами від 0 до 1:
 [[0.89171349 0.00732575 0.06940465]
 [0.1428258  0.53390618 0.87727692]
 [0.8190179  0.25271849 0.05070265]]


In [6]:
# Завдання 5. Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання, віднімання та множення.
array_a = np.random.randint(1, 21, 6)
array_b = np.random.randint(1, 21, 6)

print("Масив A:", array_a)
print("Масив B:", array_b)
print("Додавання (A + B):", array_a + array_b)
print("Віднімання (A - B):", array_a - array_b)
print("Множення (A * B):", array_a * array_b)

Масив A: [11 17 13  1 18 20]
Масив B: [ 2  6  4 18 16 16]
Додавання (A + B): [13 23 17 19 34 36]
Віднімання (A - B): [  9  11   9 -17   2   4]
Множення (A * B): [ 22 102  52  18 288 320]


In [13]:
# Завдання 6. Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.
matrix_3x2 = np.random.randint(1, 6, (3, 2))
matrix_2x4 = np.random.randint(1, 6, (2, 4))
product_matrix = np.dot(matrix_3x2, matrix_2x4)

print("Матриця 3x2:\n", matrix_3x2)
print("Матриця 2x4:\n", matrix_2x4)
print("Результат множення (матриця 3x4):\n", product_matrix)

Матриця 3x2:
 [[2 2]
 [3 5]
 [5 2]]
Матриця 2x4:
 [[3 4 2 5]
 [4 4 3 2]]
Результат множення (матриця 3x4):
 [[14 16 10 14]
 [29 32 21 25]
 [23 28 16 29]]


In [8]:
# Завдання 7. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
task7_matrix = np.random.rand(3, 3)
print("Оригінальна матриця 3x3:\n", task7_matrix)
print("Транспонована матриця:\n", task7_matrix.T)

Оригінальна матриця 3x3:
 [[0.2083117  0.59661871 0.04371713]
 [0.45093711 0.08919011 0.20928404]
 [0.60521067 0.47546381 0.39228298]]
Транспонована матриця:
 [[0.2083117  0.45093711 0.60521067]
 [0.59661871 0.08919011 0.47546381]
 [0.04371713 0.20928404 0.39228298]]


In [9]:
# Завдання 8. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
mat1_task8 = np.random.randint(1, 11, (3, 3))
mat2_task8 = np.random.randint(1, 11, (3, 3))

print("Матриця 1:\n", mat1_task8)
print("Матриця 2:\n", mat2_task8)
print("Різниця (Матриця 1 - Матриця 2):\n", mat1_task8 - mat2_task8)

Матриця 1:
 [[9 8 8]
 [9 7 6]
 [9 9 4]]
Матриця 2:
 [[ 7  9  9]
 [ 9 10  5]
 [ 3  9  9]]
Різниця (Матриця 1 - Матриця 2):
 [[ 2 -1 -1]
 [ 0 -3  1]
 [ 6  0 -5]]


In [12]:
# Завдання 9. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від -5 до 5 та знайдіть їх добуток.
mat1_task9 = np.random.randint(-5, 6, (3, 3))
mat2_task9 = np.random.randint(-5, 6, (3, 3))
product_task9 = np.dot(mat1_task9, mat2_task9)

print("Матриця 1:\n", mat1_task9)
print("Матриця 2:\n", mat2_task9)
print("Добуток матриць:\n", product_task9)

Матриця 1:
 [[-1  5 -3]
 [-2 -5  2]
 [-5  5 -4]]
Матриця 2:
 [[-2  5 -1]
 [-3  3 -2]
 [ 1 -2 -1]]
Добуток матриць:
 [[-16  16  -6]
 [ 21 -29  10]
 [ -9  -2  -1]]


In [14]:
# Завдання 10. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
task10_matrix = np.random.uniform(-1, 1, (3, 3))
row_sums_vector = np.sum(task10_matrix, axis=1).reshape(-1, 1)

print("Матриця 3x3:\n", task10_matrix)
print("Вектор-стовпчик із сумами рядків:\n", row_sums_vector)

Матриця 3x3:
 [[ 0.00130877 -0.14410916 -0.04876703]
 [ 0.61830991 -0.86097177  0.50498702]
 [-0.67535187 -0.09162751  0.71715721]]
Вектор-стовпчик із сумами рядків:
 [[-0.19156741]
 [ 0.26232516]
 [-0.04982217]]
